### ISSUE TITLE
Medium articles not available

### ISSUE THREAD

**Issue by Newtoniano** [financialnoob/pairs_trading#2]
It looks like there is an issue with your medium account, please contact them to solve whatever issue there is, your work and contributions are great and much appreciated!

**Comment by financialnoob** [comment]
I'm aware of this problem and working to resolve it. In case I can't resolve the issue with Medium, I'll move my articles somewhere else and post new links on my GitHub readme pages.

**Comment by financialnoob** [comment]
All my articles will be moved here: https://financialnoob.me

Importing data from medium doesn't work as expected, so I'm doing it manually. I will update this issue when all articles are successfully moved.

**Comment by financialnoob** [comment]
I've moved all my articles here: https://financialnoob.substack.com
