### ISSUE TITLE
Why Trading only in Granger-followers trades in leaders

### ISSUE THREAD

**Issue by zhaoyiming808** [financialnoob/pairs_trading#4]
Hello, while reading your code, I noticed that you made the leader to the first and the follower to the second in the string. However, the code in block `Trading only in Granger-followers` is written as following:

```python
    positions_short.loc[spread > mu+r*sigma, [s1,s2]] = [-1,0]
    positions_short.loc[spread < mu, [s1,s2]] = [0,0]
    positions_long.loc[spread < mu-r*sigma, [s1,s2]] = [1,0]
    positions_long.loc[spread > mu, [s1,s2]] = [0,0]
```

Looks like it is trading the s2. Is it correct? Thank you

**Comment by financialnoob** [comment]
What made you think that granger-leader is first?

**Comment by zhaoyiming808** [comment]
> What made you think that granger-leader is first?

this is my fault😅
